APPS-4242 add glue tests
spryker-sdk/spryk-src pull request #19
Opened 2022-05-21 16:42 UTC by sergeyspryker

2022-05-23 10:25 UTC, stereomon requested changes

2022-05-23 10:25 UTC, stereomon commented on src/Spryk/Model/Spryk/Executor/SprykExecutor.php
> +    private $conditionMatcher;
Please always make use of typed properties and use protected.

2022-05-23 10:25 UTC, stereomon commented on src/Spryk/Model/Spryk/Filter/HttpResponseCodeToConstantNameFilter.php
> +    protected $responseClassConstants = [];
property type is missing. Shouldn't this be a static one for performance reasons?

2022-05-23 10:25 UTC, stereomon commented on tests/SprykerSdkTest/Spryk/Model/Spryk/Executor/ConditionMatcherTest.php
> +    protected $conditionMatcher;
Property type is missing

2022-05-23 10:25 UTC, stereomon commented on tests/SprykerSdkTest/Spryk/Model/Spryk/Executor/ConditionMatcherTest.php
> +        parent::setUp();
I personally don't like to use this approach. What's against using `\SprykerSdkTest\Module\SprykHelper::getClass()` or adding your own method to get this service from the tester as done with e.g. `\SprykerSdkTest\Module\SprykHelper::getClassDumper()`?

2022-05-23 10:25 UTC, stereomon commented on tests/SprykerSdkTest/Spryk/Model/Spryk/Filter/HttpResponseCodeToConstantNameFilterTest.php
> +            $this->filter = new HttpResponseCodeToConstantNameFilter();
Tests also must make use of the DependencyInjection container.

2022-05-23 13:05 UTC, sergeyspryker commented on config/spryk/spryks/Spryker/Glue/Test/AddGlueTestTester.yml
> +                value: "seeResponseJsonContains{{ zedDomainEntity }}IdWithUuid"
But we check Id and Uuid

2022-05-23 15:28 UTC, sergeyspryker commented on config/spryk/templates/Glue/Test/GlueTestApiCest/ApiCest.php.twig
> +        $this->fixtures = $fixtures;
Was added due to return value typeHint

2022-05-24 08:04 UTC, stereomon approved these changes

2022-06-02 16:46 UTC, merged