APPS-4309 add docs
spryker-sdk/spryk-src pull request #21
Opened 2022-05-25 13:47 UTC by sergeyspryker

2022-05-25 14:19 UTC, dereuromark commented on docs/Spryk configuration reference.md
> +All the spryks configs are located in `config/spryk/spryks` directory.
```suggestion
All the spryks configs are located in `config/spryk/spryks/` directory.
```

2022-05-25 14:20 UTC, dereuromark commented on docs/Spryk configuration reference.md
> +The pre-processing callback that will be applied on value before passing into the spryk. Should implement `\SprykerSdk\Spryk\Model\Spryk\Definition\Argument\Callback\CallbackInterface`.
leading \ is void here (not needed).

2022-05-30 10:58 UTC, stereomon requested changes
I only reviewed half of the document. Please make sure to use `Spryk` and `Spryks` in capital form. There is also a lot to do in terms of the used grammar.

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +
One new line is enough.

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +## Building the new spryks
```suggestion
## Add a new Spryk
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +Depends on what builder is used the appropriate number of arguments you should to define.
```suggestion
To add a new Spryk you need to add a YAML configuration in the `config/spryk/spryks/` directory. 

The `spryk` option defines which builder is used to work with the defined Spryk definition. 

Example: `spryk: Template` will use the `\SprykerSdk\Spryk\Model\Spryk\Builder\Template\TemplateSpryk` class to fulfill the Spryk definition.
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +The spryk can depend on some other spryks and in this case some other spryks should be executed before or after. It looks like a tree (or even a graph in some cases) structure that's controlled by
```suggestion
Spryks can depend on other Spryks that will be executed before or after the current Spryk is executed. It looks like a tree (or even a graph in some cases) structure that's controlled by
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +But in another hand the deep hierarchical structure hard to debug that is why try not to create deep structures and use only the required dependencies.
```suggestion
A best practice is when a Spryk builds only one small structural unit and calls other Spryks that build all rest of the needed structures (classes, interfaces, configs, and so on). When someone executes a Spryk he should get a completely valid structure of files.
```

I'm not understanding the last sentence at all.

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +The arguments of the children spryks can inherit the values of the same arguments of the paren spryks. To achieve that you should define [`inherit: true`](/docs/spryk_configuration_reference.md#inher
```suggestion
The arguments of the children's Spryks can inherit the values of the same arguments of the parent Spryk. To achieve that you need to define the [`inherit: true`](/docs/spryk_configuration_reference.md#inherit) option in the argument definition block.
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +### The spryks overriding
```suggestion
### Overriding arguments in pre/postSpryks
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +The spryk overriding is useful for customisation the existing spryks in `preSpryks` or `postSpryks` by passing or overriding the arguments. You can even pass the arguments that are not defined in ove
```suggestion
Overriding is useful for the customization of a used Spryk in the `preSpryks` or `postSpryks` section. You can pass or override arguments here. 

You can even add arguments that are not defined in the used Spryk itself. This is mainly useful when you use a Twig template with more arguments than the original used template has.
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +if you don't need the full hierarchy of overridden spryk you can manipulate it by `excludedSpryks` option.
```suggestion
As explained before, you can look at Spryks as some sort of hierarchy where one Spryk uses several other Spryks. In some cases, you don't need the full hierarchy. To exclude the execution of one or more Spryks you can use the `excludedSpryks` option.
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +### How to use spryk condition
```suggestion
### Conditional Spryks
```

2022-05-30 10:58 UTC, stereomon commented on docs/building_new_spryks.md
> +Useful when you need to limit some spryk execution by some conditions. For example in one case you need to create one method in another case another method.
```suggestion
In some cases, you need to run a Spryk only when a specific condition is matched. For example one of the passed arguments has a specific value. For these cases, you can use the `condition` option.
```

2022-05-30 12:07 UTC, stereomon commented on docs/developer_guige.md
> +To check what the files were generated without the affecting of the `codeSniffer` need to pass `TESTING=true` env variable into the command.
```suggestion
To check how files look after generating them without running the CodeSniffer you need to disable the CodeSniffer by prefixing the console command with `TESTING=true`.
```

2022-05-30 12:09 UTC, stereomon commented on docs/developer_guige.md
> +`SprykerSdk\Spryk\Model\Spryk\Builder\AbstractBuilder::getTargetPath()`
Please explain the diff between each ideally with examples.

2022-05-30 12:10 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +and should implement `SprykerSdk\Spryk\Model\Spryk\Builder\SprykBuilderInterface::getName()`.
must

2022-05-30 12:11 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +Description of the spryk. Should be populated for every spryk for the informational purposes.
```suggestion
Description of the spryk. Must be added to give the reader of the Spryk definition a clear description of what this Spryk is doing.
```

2022-05-30 12:12 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +The mode of the spryk. It used for running the specific spryks by passing the `--mode` option into the command. The reserved `both` value allows to run spryk in any case.
Explain all three cases, please.

2022-05-30 12:15 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +The argument default value if not set.
```suggestion
The default value for the argument if not passed from CLI.
```

2022-05-30 12:15 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +The argument value that can be set. Useful when need to compose value from another arguments values or/and apply some twig filters or functions.
```suggestion
The argument value that will be used. Useful when need to compose value from another arguments values or/and apply some twig filters or functions.
```

2022-05-30 12:17 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +If argument is optional the values can be empty otherwise the argument value should be provided.
Please add a note that the default value for this is `false` which means it is required by default.

2022-05-30 12:17 UTC, stereomon commented on docs/spryk_configuration_reference.md
> +          - "three"
I don't see `isMultiple` in this list. As user I would not know where to put this to.

2022-06-02 17:03 UTC, merged