FRW-112 fixed redeclared const issue
spryker-sdk/spryk-src pull request #58
Opened 2022-07-25 13:26 UTC by olhalivitchuk

- Developer(s): @olhalivitchuk 

- Ticket: https://spryker.atlassian.net/browse/FRW-112

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SprykSrc              | patch (currently 0.0.x)  |                       |

-----------------------------------------

#### Module SprykSrc

##### Change log

### Fixes

- Added `APPLICATION_ENV_SPRYK_USAGE` instead of redeclaring `APPLICATION_ENV` so it does not throw the exception if the constant has been already defined.

2022-07-25 13:56 UTC, yaroslav-spryker requested changes

2022-07-25 13:56 UTC, yaroslav-spryker commented on bin/environment.php
> +define('APPLICATION_ENV_SPRYK_USAGE', $applicationEnv !== false && in_array($applicationEnv, $allowedApplicationEnvs, true) ? $applicationEnv : 'prod');
Lets rename this constant to `APPLICATION_ENV_SPRYK`

2022-07-26 08:41 UTC, gechetspr approved these changes
But please check why CI is failing. Previous commits has a green CI

2022-08-01 10:37 UTC, yaroslav-spryker approved these changes

2022-08-02 08:42 UTC, merged