FRW-1790: Fixed spryk failing due to missed Stopwatch extension
spryker-sdk/spryk-src pull request #77
Opened 2023-06-19 17:41 UTC by olhalivitchuk

Ticket: https://spryker.atlassian.net/browse/FRW-1790

- Updated `box.phar` to support `PHP>8.0` version.
- Adjusted `scoper.inc.php` to return an array with valid configuration keys.
- Added `Symfony.Stopwatch` component to `composer.json` to not throw the exception.

2023-06-20 07:53 UTC, yaroslav-spryker requested changes

2023-06-20 07:53 UTC, yaroslav-spryker commented on compiler/build/box.phar
Please return 0755 permissions to this file

2023-06-20 08:02 UTC, dimitriyTsemma reviewed
can you, please fix CI validation errors?

2023-06-20 11:06 UTC, yaroslav-spryker approved these changes

2023-08-01 11:32 UTC, asmarovydlo approved these changes

2023-08-01 11:41 UTC, merged